#!/bin/bash

TEST=$(transmission-remote IP:PORT --auth USER:PASS --list)

main ()
        {

        TOTAL=$(echo "$TEST" | wc -l)
        ACTUAL=$(($TOTAL-1))
        echo "Total: $ACTUAL"

        STOPPED=$(echo "$TEST" | grep "Stopped" | wc -l)
        echo "Stopped: $STOPPED"

        DOWNLOADING=$(echo "$TEST" | grep "Downloading" | wc -l)
        echo "Downloading: $DOWNLOADING"

        FINISHED=$(echo "$TEST" | grep "Finished" | wc -l)
        echo "Finished: $FINISHED"

        exit 0;

        }

main;
